# Generated by Django 4.2.6 on 2023-11-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50)),
                ("body", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("junior_id", models.IntegerField()),
                ("senior_id", models.IntegerField(null=True)),
                ("status", models.CharField(max_length=10)),
            ],
        ),
    ]
