# Generated by Django 4.2.7 on 2024-01-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=50)),
                ("body", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=10)),
                ("junior_id", models.IntegerField()),
                ("senior_id", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "issues",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("content", models.CharField(max_length=255)),
                ("author_id", models.IntegerField()),
                ("issue_id", models.IntegerField()),
            ],
            options={
                "db_table": "issues/messages",
            },
        ),
    ]
