name: Code quality

on: [pull_request]

jobs:
  code-quality:
    runs-on: python:3.11-slim # ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install ruff black isort
    - name: run linter
      run: ruff check .
    - name: run formatters
      run: black -t py311 --check . && isort --check .
